apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: __REPLICAS__
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: __BRANCH_NAME__-__BUILD_NUMBER__-__BUILD_ID__
        image: nginx:1.16.1 # Update the version of nginx from 1.14.2 to 1.16.1
        ports:
        - containerPort: 80
--
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: __PROTOCOL__
  selector:
    run: my-nginx