# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Extract Branch Name
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Runs a set of commands using the runners shell
      - name: Replace env vars in file
        uses: falnyr/replace-env-vars-action@v1.2.1
        with:
          filename: ./k8s-config.yaml
        env:
          REPLICAS: 2
          PROTOCOL: TCP
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_ID: ${{ github.run_id }}

      # Runs a single command using the runners shell
      - name: Cat k8s-config.yaml
        run: cat k8s-config.yaml

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          files: ./Dockerfile
          push: true
          tags: markwhelancsm/actions:${{ steps.extract_branch.outputs.branch }}-${{ github.run_number }}-${{ github.run_id }}, markwhelancsm/actions:${{ steps.extract_branch.outputs.branch }}-latest

      - name: Copy File to Flux Repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'k8s-config.yaml'
          destination_repo: 'markwdevops/flux'
          destination_folder: 'k8s-cluster'
          user_email: 'markwdevops@gmail.com'
          user_name: 'markwdevops'
          commit_message: 'Copy File to Flux'

